#!/usr/bin/env python3
"""Writes shared/NRSSTrustAnchors.c: BearSSL trust anchors for every root in a PEM bundle (default: the
host's Mozilla-derived CA bundle). Equivalent to `brssl ta`, without running any vendored tool."""
import sys
import warnings
from pathlib import Path
from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import ec, rsa
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

bundle = Path(sys.argv[1] if len(sys.argv) > 1 else '/etc/ssl/certs/ca-certificates.crt')
out = Path(__file__).resolve().parent.parent / 'shared' / 'NRSSTrustAnchors.c'
CURVES = {'secp256r1': 'BR_EC_secp256r1', 'secp384r1': 'BR_EC_secp384r1', 'secp521r1': 'BR_EC_secp521r1'}


def blob(name, data):
    rows = [', '.join('0x%02X' % b for b in data[i:i + 12]) for i in range(0, len(data), 12)]
    return 'static const unsigned char %s[] = {\n\t%s\n};\n' % (name, ',\n\t'.join(rows))


with warnings.catch_warnings():
    warnings.simplefilter('ignore')  # some old roots carry non-positive serial numbers
    certs = x509.load_pem_x509_certificates(bundle.read_bytes())
parts, anchors, seen = [], [], set()
for cert in certs:
    key = cert.public_key()
    dn = cert.subject.public_bytes()
    identity = dn + key.public_bytes(Encoding.DER, PublicFormat.SubjectPublicKeyInfo)
    if identity in seen:
        continue
    i = len(anchors)
    if isinstance(key, rsa.RSAPublicKey):
        numbers = key.public_numbers()
        n = numbers.n.to_bytes((numbers.n.bit_length() + 7) // 8, 'big')
        e = numbers.e.to_bytes((numbers.e.bit_length() + 7) // 8, 'big')
        parts += [blob('TA%d_DN' % i, dn), blob('TA%d_RSA_N' % i, n), blob('TA%d_RSA_E' % i, e)]
        anchors.append('\t{ { (unsigned char *)TA%d_DN, sizeof TA%d_DN }, BR_X509_TA_CA, { BR_KEYTYPE_RSA, { .rsa = { '
                       '(unsigned char *)TA%d_RSA_N, sizeof TA%d_RSA_N, (unsigned char *)TA%d_RSA_E, sizeof TA%d_RSA_E } } } }'
                       % ((i,) * 6))
    elif isinstance(key, ec.EllipticCurvePublicKey) and key.curve.name in CURVES:
        q = key.public_bytes(Encoding.X962, PublicFormat.UncompressedPoint)
        parts += [blob('TA%d_DN' % i, dn), blob('TA%d_EC_Q' % i, q)]
        anchors.append('\t{ { (unsigned char *)TA%d_DN, sizeof TA%d_DN }, BR_X509_TA_CA, { BR_KEYTYPE_EC, { .ec = { '
                       '%s, (unsigned char *)TA%d_EC_Q, sizeof TA%d_EC_Q } } } }' % (i, i, CURVES[key.curve.name], i, i))
    else:
        continue
    seen.add(identity)

out.write_text('// Generated by scripts/make-trust-anchors.py from %s (%d roots). Do not edit.\n'
               '#include "bearssl.h"\n#include "NRSSTrustAnchors.h"\n\n%s\n'
               'const br_x509_trust_anchor NRSSTrustAnchors[] = {\n%s\n};\n'
               'const size_t NRSSTrustAnchorCount = sizeof NRSSTrustAnchors / sizeof NRSSTrustAnchors[0];\n'
               % (bundle, len(anchors), '\n'.join(parts), ',\n'.join(anchors)))
print('%d trust anchors -> %s' % (len(anchors), out))
